"""Core data models for AlphaEvo."""

from alphaevo.models.enums import EvolutionMethod, MarketRegime, MarketType, StrategyCategory
from alphaevo.models.execution import (
    AntiFitMetrics,
    BacktestResult,
    CandidateExperiment,
    CPCVMetrics,
    EvaluationReport,
    EventContextMetrics,
    EvolutionNode,
    OverallMetrics,
    ReflectionResult,
    RegimeHoldoutCase,
    RegimeHoldoutMetrics,
    RegimeMetrics,
    ResearchHypothesis,
    SampleBatch,
    SamplingAttempt,
    StrategyChange,
    StressWindowCase,
    StressWindowMetrics,
    TradeSignal,
    WalkForwardFoldMetrics,
    WalkForwardProtocol,
)
from alphaevo.models.market import (
    EventContextRecord,
    EventContextSeries,
    FundamentalData,
    IndicatorContext,
    MarketContext,
    MarketSnapshot,
    NewsItem,
    PriceData,
    RealTimeQuote,
    SectorInfo,
    StockInfo,
    TechnicalIndicators,
    VolumeData,
)
from alphaevo.models.strategy import (
    ExecutionConfig,
    MarketHypothesisAssessment,
    MarketHypothesisSummary,
    MarketRuleConfig,
    StopLossConfig,
    Strategy,
    StrategyCondition,
    StrategyEntry,
    StrategyExit,
    StrategyMeta,
    StrategyParams,
    TakeProfitConfig,
    TunableParam,
    UniverseConfig,
    UniverseFilter,
)

__all__ = [
    # Enums
    "MarketType",
    "StrategyCategory",
    "MarketRegime",
    "EvolutionMethod",
    # Market
    "PriceData",
    "VolumeData",
    "TechnicalIndicators",
    "FundamentalData",
    "NewsItem",
    "EventContextRecord",
    "EventContextSeries",
    "MarketContext",
    "MarketSnapshot",
    "RealTimeQuote",
    "StockInfo",
    "SectorInfo",
    "IndicatorContext",
    # Strategy
    "StrategyMeta",
    "StrategyCondition",
    "ExecutionConfig",
    "StrategyEntry",
    "StopLossConfig",
    "TakeProfitConfig",
    "StrategyExit",
    "UniverseFilter",
    "UniverseConfig",
    "TunableParam",
    "StrategyParams",
    "MarketRuleConfig",
    "MarketHypothesisSummary",
    "MarketHypothesisAssessment",
    "Strategy",
    # Execution
    "SampleBatch",
    "SamplingAttempt",
    "TradeSignal",
    "BacktestResult",
    "OverallMetrics",
    "RegimeMetrics",
    "AntiFitMetrics",
    "EvaluationReport",
    "EventContextMetrics",
    "RegimeHoldoutCase",
    "RegimeHoldoutMetrics",
    "StressWindowCase",
    "StressWindowMetrics",
    "CPCVMetrics",
    "WalkForwardFoldMetrics",
    "WalkForwardProtocol",
    "StrategyChange",
    "ResearchHypothesis",
    "CandidateExperiment",
    "ReflectionResult",
    "EvolutionNode",
]
