"""LLM-driven factor hypothesis generation.

Asks the LLM to propose new technical indicators based on failure context,
then parses the response into structured FactorHypothesis objects.
"""

from __future__ import annotations

import logging
import re
from typing import TYPE_CHECKING, Literal

from pydantic import BaseModel

if TYPE_CHECKING:
    from alphaevo.core.llm import LLMClient

logger = logging.getLogger(__name__)

_SYSTEM_PROMPT = """\
You are a quantitative factor researcher. Your job is to invent new technical
indicators computed purely from OHLCV (Open, High, Low, Close, Volume) data.

Each indicator must be a Python function with this EXACT signature:
    def compute(df: pd.DataFrame, idx: int) -> float

Rules:
- df has columns: open, high, low, close, volume (all lowercase)
- idx is the current bar index (0-based); you may look back but NOT forward
- Only use: numpy, pandas, math (already imported as np, pd, math)
- Return a single float value
- Handle edge cases (e.g., idx < lookback → return 0.0)
- Do NOT use exec, eval, open, os, sys, subprocess, __import__
- Keep it under 30 lines

Output JSON array with this schema:
[
  {
    "name": "my_factor_name",
    "description": "one-line human-readable description",
    "rationale": "why this factor should predict returns",
    "code": "def compute(df, idx):\\n    ...",
    "expected_direction": "positive"
  }
]
"""

_USER_TEMPLATE = """\
Context for factor generation:
- Current strategy failure: {context}
- Existing indicators (avoid duplicates): {existing}
- Previously failed factor attempts: {failed}

Generate {count} new factor candidates. Each must capture a DIFFERENT market
phenomenon (e.g., momentum, volatility regime, volume pattern, mean-reversion).
"""


class FactorHypothesis(BaseModel):
    """A single factor candidate generated by the LLM."""

    name: str
    description: str
    rationale: str
    code: str
    expected_direction: Literal["positive", "negative"] = "positive"


class FactorSynthesizer:
    """Generate factor candidates using an LLM.

    Example::

        synth = FactorSynthesizer(llm_client)
        hypotheses = await synth.generate(
            context="Low win rate due to false breakouts",
            existing_factors=["rsi_14", "ma5_above_ma10"],
        )
    """

    def __init__(self, llm_client: LLMClient) -> None:
        self._llm = llm_client

    async def generate(
        self,
        context: str,
        existing_factors: list[str],
        *,
        failed_attempts: list[str] | None = None,
        max_candidates: int = 3,
    ) -> list[FactorHypothesis]:
        """Generate factor candidates from context."""
        user_msg = _USER_TEMPLATE.format(
            context=context,
            existing=", ".join(existing_factors) if existing_factors else "none",
            failed=", ".join(failed_attempts) if failed_attempts else "none",
            count=max_candidates,
        )

        messages = [
            {"role": "system", "content": _SYSTEM_PROMPT},
            {"role": "user", "content": user_msg},
        ]

        try:
            raw = self._llm.chat_json(messages, temperature=0.6, max_tokens=4096)
        except Exception:
            logger.exception("LLM factor generation failed")
            return []

        return self._parse_response(raw)

    async def refine(
        self,
        hypothesis: FactorHypothesis,
        error_message: str,
    ) -> FactorHypothesis | None:
        """Refine a factor that failed validation/execution."""
        messages = [
            {"role": "system", "content": _SYSTEM_PROMPT},
            {
                "role": "user",
                "content": (
                    f"The following factor failed with error:\n"
                    f"Name: {hypothesis.name}\n"
                    f"Code:\n```python\n{hypothesis.code}\n```\n"
                    f"Error: {error_message}\n\n"
                    f"Fix the code and return a single corrected factor as a JSON array."
                ),
            },
        ]

        try:
            raw = self._llm.chat_json(messages, temperature=0.3, max_tokens=2048)
        except Exception:
            logger.exception("LLM factor refinement failed")
            return None

        candidates = self._parse_response(raw)
        return candidates[0] if candidates else None

    @staticmethod
    def _parse_response(raw: dict | list) -> list[FactorHypothesis]:
        """Parse LLM JSON response into FactorHypothesis objects."""
        # Handle both direct list and wrapped responses
        if isinstance(raw, dict):
            # Try common wrapper keys
            for key in ("factors", "candidates", "results", "data"):
                if key in raw and isinstance(raw[key], list):
                    raw = raw[key]
                    break
            else:
                # Single factor wrapped in dict
                raw = [raw]

        if not isinstance(raw, list):
            return []

        results = []
        for item in raw:
            if not isinstance(item, dict):
                continue
            try:
                # Normalize the code field
                code = item.get("code", "")
                if not code:
                    continue
                # Strip markdown code fences if present
                code = re.sub(r"^```(?:python)?\n?", "", code)
                code = re.sub(r"\n?```$", "", code)
                item["code"] = code.strip()

                hyp = FactorHypothesis.model_validate(item)
                results.append(hyp)
            except Exception:
                logger.debug("Skipping invalid factor hypothesis: %s", item)
                continue

        return results
