"""Factor CLI sub-commands."""

from __future__ import annotations

import asyncio
from datetime import date, timedelta
from pathlib import Path
from typing import Any

import typer
from rich.console import Console
from rich.panel import Panel
from rich.progress import Progress, SpinnerColumn, TextColumn
from rich.table import Table

from alphaevo.cli._helpers import _get_config

factor_app = typer.Typer(help="Alpha factor management commands")
console = Console()


def _render_factor_discovery_report(
    symbol: str,
    context: str,
    result: Any,
    *,
    factor_store: Any | None = None,
) -> str:
    """Build a readable Markdown report for one factor discovery run."""
    lines = [
        "# Factor Discovery Report",
        "",
        f"**Symbol**: {symbol}",
        f"**Context**: {context or '—'}",
        "",
        "## Summary",
        "",
        f"- Proposed: {len(result.proposed)}",
        f"- Sandbox passed: {len(result.sandbox_passed)}",
        f"- Sandbox failed: {len(result.sandbox_failed)}",
        f"- Validation passed: {len(result.validation_passed)}",
        f"- Validation failed: {len(result.validation_failed)}",
        f"- Registered: {len(result.registered)}",
        "",
    ]

    if result.proposed:
        lines += ["## LLM Proposals", ""]
        for hyp in result.proposed:
            lines.append(f"### {getattr(hyp, 'name', 'unnamed_factor')}")
            lines.append(f"- Description: {getattr(hyp, 'description', '—')}")
            lines.append(f"- Rationale: {getattr(hyp, 'rationale', '—')}")
            expected_direction = getattr(hyp, "expected_direction", None)
            if expected_direction:
                lines.append(f"- Expected direction: {expected_direction}")
            lines.append("")

    if result.sandbox_failed:
        lines += ["## Sandbox Failures", ""]
        for name, error in result.sandbox_failed:
            lines.append(f"- `{name}`: {error}")
        lines.append("")

    if result.validation_failed:
        lines += ["## Validation Failures", ""]
        for name, reasons in result.validation_failed:
            reason_text = "; ".join(reasons) if reasons else "unknown validation failure"
            lines.append(f"- `{name}`: {reason_text}")
        lines.append("")

    if result.registered:
        lines += ["## Registered Factors", ""]
        for name in result.registered:
            record = factor_store.get(name) if factor_store is not None else None
            lines.append(f"### {name}")
            if record is None:
                lines.append("- Metrics unavailable")
                lines.append("")
                continue
            lines.append(f"- Description: {record.description}")
            lines.append(f"- Rationale: {record.rationale}")
            lines.append(
                f"- IC Mean: {record.ic_mean:.3f} | IR: {record.ir:.2f} | "
                f"Monthly Win Rate: {record.monthly_win_rate:.1%} | "
                f"Turnover: {record.turnover:.1%}"
            )
            lines.append(f"- Status: {record.status}")
            lines.append("")

    lines += [
        "---",
        "*Generated by AlphaEvo factor discovery. Results are research-only, not investment advice.*",
        "",
    ]
    return "\n".join(lines)


@factor_app.command("list")
def factor_list() -> None:
    """List all registered alpha factors."""
    config = _get_config()
    from alphaevo.alpha_factory import FactorStore

    store = FactorStore(config.db_path)
    try:
        factors = store.list_all()
        if not factors:
            console.print("[yellow]No factors registered yet.[/yellow]")
            return

        table = Table(title="Alpha Factors")
        table.add_column("Name", style="cyan")
        table.add_column("IC Mean", justify="right")
        table.add_column("IR", justify="right")
        table.add_column("Status")
        for f in factors:
            table.add_row(
                f.name,
                f"{f.ic_mean:.3f}" if f.ic_mean else "—",
                f"{f.ir:.2f}" if f.ir else "—",
                f.status,
            )
        console.print(table)
    finally:
        store.close()


@factor_app.command("show")
def factor_show(name: str = typer.Argument(..., help="Factor name")) -> None:
    """Show details of a specific factor."""
    config = _get_config()
    from alphaevo.alpha_factory import FactorStore

    store = FactorStore(config.db_path)
    try:
        record = store.get(name)
        if record is None:
            console.print(f"[red]Factor not found: {name}[/red]")
            raise typer.Exit(1)

        console.print(
            Panel(
                f"[bold]{record.name}[/bold]\n"
                f"{record.description}\n\n"
                f"IC Mean: {record.ic_mean:.3f} | IR: {record.ir:.2f} | "
                f"Monthly Win Rate: {record.monthly_win_rate:.1%}\n"
                f"Status: {record.status}",
                title="Alpha Factor",
                style="cyan",
            )
        )
        if record.code:
            console.print(Panel(record.code, title="Code", style="dim"))
    finally:
        store.close()


@factor_app.command("retire")
def factor_retire(name: str = typer.Argument(..., help="Factor name to retire")) -> None:
    """Retire (soft-delete) a factor."""
    config = _get_config()
    from alphaevo.alpha_factory import FactorStore

    store = FactorStore(config.db_path)
    try:
        record = store.get(name)
        if record is None:
            console.print(f"[red]Factor not found: {name}[/red]")
            raise typer.Exit(1)
        store.retire(name)
        console.print(f"[green]✓[/green] Retired factor: {name}")
    finally:
        store.close()


@factor_app.command("discover")
def factor_discover(
    symbol: str = typer.Argument(..., help="Stock symbol for factor discovery"),
    context: str | None = typer.Option(None, "--context", "-c", help="Discovery context"),
    output_file: str | None = typer.Option(None, "--output", "-o", help="Report output path"),
) -> None:
    """Discover new alpha factors using LLM analysis."""
    config = _get_config()

    with Progress(
        SpinnerColumn(),
        TextColumn("[progress.description]{task.description}"),
        console=console,
    ) as progress:
        progress.add_task("Discovering factors...", total=None)

        try:
            df = asyncio.run(_load_factor_history(config, symbol))
        except Exception as e:
            console.print(f"[red]Data load failed: {e}[/red]")
            raise typer.Exit(1) from None

        from alphaevo.alpha_factory import AlphaFactory, load_registered_factors
        from alphaevo.core.llm import LLMClient

        llm = LLMClient.from_config(config)
        load_registered_factors(config.db_path)
        factory = AlphaFactory(llm_client=llm, db_path=config.db_path)

        try:
            result = asyncio.run(
                factory.discover(
                    context=context or "",
                    ohlcv_data=df,
                    forward_returns=_build_forward_returns(df),
                    dates=df["date"] if "date" in df.columns else None,
                )
            )
        except Exception as e:
            console.print(f"[red]Discovery failed: {e}[/red]")
            raise typer.Exit(1) from None

    console.print(f"[green]✓[/green] Proposed: {len(result.proposed)}")
    console.print(f"  Sandbox passed: {len(result.sandbox_passed)}")
    console.print(f"  Validation passed: {len(result.validation_passed)}")
    console.print(f"  Registered: {len(result.registered)}")

    if output_file:
        output_path = Path(output_file)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        from alphaevo.alpha_factory import FactorStore

        store = FactorStore(config.db_path)
        try:
            report_md = _render_factor_discovery_report(symbol, context or "", result, factor_store=store)
        finally:
            store.close()
        output_path.write_text(report_md, encoding="utf-8")
        console.print(f"\n📄 Report saved to: {output_file}")


async def _load_factor_history(config: Any, symbol: str, days: int = 120) -> Any:
    """Load historical data for factor discovery."""
    from alphaevo.data.adapter import DataManager, get_adapter
    from alphaevo.data.cache import DataCache

    end = date.today()
    start = end - timedelta(days=max(days - 1, 0))
    manager = DataManager(
        [get_adapter(config)],
        cache=DataCache(config.data.cache_dir),
    )
    return await manager.get_history(symbol, start, end)


def _build_forward_returns(df: Any, horizon: int = 5) -> Any:
    """Build a simple forward-return series for factor validation."""
    if "close" not in df.columns:
        raise ValueError("Historical data must include a 'close' column")
    close = df["close"].astype(float)
    return close.shift(-horizon) / close - 1.0
